// <auto-generated />
using System;
using Googlekeep.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Googlekeep.Migrations
{
    [DbContext(typeof(GooglekeepContext))]
    [Migration("20180802125406_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Googlekeep.Model.checklist", b =>
                {
                    b.Property<int>("checkID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NoteID");

                    b.Property<string>("chklist");

                    b.HasKey("checkID");

                    b.HasIndex("NoteID");

                    b.ToTable("checklist");
                });

            modelBuilder.Entity("Googlekeep.Model.label", b =>
                {
                    b.Property<int>("labelID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NoteID");

                    b.Property<string>("labelstring");

                    b.HasKey("labelID");

                    b.HasIndex("NoteID");

                    b.ToTable("label");
                });

            modelBuilder.Entity("Googlekeep.Model.Note", b =>
                {
                    b.Property<int>("NoteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ispinnned");

                    b.Property<string>("plain_text");

                    b.Property<string>("title");

                    b.HasKey("NoteID");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("Googlekeep.Model.checklist", b =>
                {
                    b.HasOne("Googlekeep.Model.Note")
                        .WithMany("ListofChecks")
                        .HasForeignKey("NoteID");
                });

            modelBuilder.Entity("Googlekeep.Model.label", b =>
                {
                    b.HasOne("Googlekeep.Model.Note")
                        .WithMany("ListofLabels")
                        .HasForeignKey("NoteID");
                });
#pragma warning restore 612, 618
        }
    }
}
